<?php

/**
 * @file
 * Contains embed_view.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function embed_view_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the render_menu module.
    case 'help.page.embed_view':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Embed view in twig templates') . '</p>';
      return $output;

    default:
  }
}

function embed_view_theme() {
  $theme = [];

  return $theme;
}
